// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.wpe.abkhazia.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ru.wpe.abkhazia.domain.Entity;

privileged aspect Entity_Roo_Configurable {
    
    declare @type: Entity: @Configurable;
    
}
