// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.wpe.abkhazia.domain;

import ru.wpe.abkhazia.domain.Entity;

privileged aspect Entity_Roo_Jpa_Entity {
    
    declare @type: Entity: @javax.persistence.Entity;
    
}
